name: CI

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install pip
        uses: BSFishy/pip-action@v1
        with:
          requirements: requirements.txt
          
      - name: Transfer to S3 for serving static
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: hackerton
          AWS_ACCESS_KEY_ID: ${{ secrets. AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}



#       - name: Install dependencies
#         run: pip install -r requirements.txt

#       - name: Make zip file
#         run: zip -qq -r ./$GITHUB_SHA.zip .
#         shell: bash

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ${{ secrets.AWS_REGION }}

#       - name: Upload to S3
#         run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://hackerton/$PROJECT_NAME/$GITHUB_SHA.zip

#       - name: Code Deploy
#         run: aws deploy create-deployment --application-name Hackerton --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name dev --s3-location bucket=hackerton,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip
